### ISSUE TITLE
ORCID authentication

### ISSUE THREAD

**Issue by guillaumegodet** [CRISalid-esr/SoVisuPlus#10]
If the user has an ORCID account, he presses the button "Log in with ORCID" and then he is redirected to an ORCID authentication page where he can insert his ORCID ID / password ang give writing authorizations to SoVisu+ application. After that he is connected to SoVisu+ with a green ORCID logo.

**Comment by jdp1ps** [comment]
The first time a user connects to SoVisu+, we may have no ORCID for her/his account, or have a wrong ORCID, or an ORCID which is not the one he usually uses.
In any case, the ORCId we have is a low quality one as it has not been prooved by Oauth2 authentication against ORCID system.
An institution may not allow people to authenticate with a non-verified ORCID and may request users to authenticate a least one with their institutional account, to go into the process of certifying their ORCID and allowing authentication trhough ORCID.
This should be an option set at application level.
