### ISSUE TITLE
Publications page : table display

### ISSUE THREAD

**Issue by guillaumegodet** [CRISalid-esr/SoVisuPlus#13]
The user presses "Publications" on the left menu, Sovisu+database has already been synchronized with the knowledge graph, then the user views a table with the list of his publications : 
https://www.figma.com/proto/X2R1T0hXbBSX1SqcvhQ3Qb/SVP%2B-Design-Kit?node-id=57418-41108&node-type=frame&t=UkkyOOTU2oH2pREH-1&scaling=min-zoom&content-scaling=fixed&page-id=57418%3A35934&starting-point-node-id=57418%3A40336

If the list is empty, a message appears : "update your account with your identifiers and come back". 

Ideally, the institution decides the columns fields that appear by default . 
If not possible, the fields that appear in the table by default would be : type, title, authors, publication date, journal, HAL status, number of versions, (to complete following the data we're collecting). 
Columns that are not erasable : title & authors 
Every column has a picto to order the data : alphabetically for text or chronological for date.
In the column HAL status, if the status implies an action that need to be done by the user there will be a picto next to the field name.

**Comment by silvibiblio** [comment]
Change the table to use the Mui component select by Guillaume
