### ISSUE TITLE
Responsive page layout 

### ISSUE THREAD

**Issue by silvibiblio** [CRISalid-esr/SoVisuPlus#30]
Responsive layout : 

- [x] Desktp/laptop : The left menu is open by default. To close it, the user will click on a picto
- [x] Mobile device : The left menu  is closed by default. To open it, the user will click on a picto
https://www.figma.com/proto/X2R1T0hXbBSX1SqcvhQ3Qb/SVP%2B-Design-Kit?node-id=57418-41108&node-type=frame&t=UkkyOOTU2oH2pREH-1&scaling=min-zoom&content-scaling=fixed&page-id=57418%3A35934&starting-point-node-id=57418%3A40336

Page layout : 

- [x] On every page the user will find a language button on the top right corner  'EN | FR'

**Comment by guillaumegodet** [comment]
The "My Account" block is fixed at the bottom left of the browser, just like on https://mantisdashboard.io/dashboard/analytics.

**Comment by jdp1ps** [comment]
When language or theme switcher get the focus, they are not highlighted

**Comment by jdp1ps** [comment]
> When language or theme switcher get the focus, they are not highlighted

**Comment by silvibiblio** [comment]
accessibilty issues (https://www.youtube.com/watch?v=YhlAVlfH0rQ&ab_channel=MozillaDeveloper) :

- [ ] add a name to the page
- [ ] add text labels or use proper aria-label tag or attributes
- [ ] Do not use tag img for icons and follow this advice for icons https://optasy.com/blog/10-best-practices-making-web-icons-accessible
